name: Generate Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-activity-graph
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: Ashutosh00710/github-readme-activity-graph@v1.2.3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          output_filepath: activity-graph.svg
          theme: tokyonight
          area: true
          hide_border: true

      - name: Commit & Push Activity Graph
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add activity-graph.svg
          git commit -m "Update activity graph" || exit 0
          git push
